name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Date
        id: get-date
        run: echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_ENV

      - name: Check buildozer.spec
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "Error: buildozer.spec not found!"
            exit 1
          fi

      - name: Install dependencies
        run: |
          apt update
          apt install -y python3-pip openjdk-17-jdk
          pip3 install --upgrade Cython virtualenv
          pip3 install --upgrade buildozer

      - name: Cache Buildozer global
        uses: actions/cache@v2
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer
        uses: actions/cache@v2
        with:
          path: .buildozer
          key: buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Initialize Buildozer
        run: buildozer init

      - name: Build with Buildozer
        run: buildozer -v android debug | tee buildozer.log

      - name: Find APK file
        run: |
          echo "Looking for APK file..."
          find . -name "*.apk"
          ls -l bin/ || echo "No bin directory found."

      - name: Upload Build Log
        uses: actions/upload-artifact@v2
        with:
          name: build-log
          path: buildozer.log

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: bin/*.apk
